### PR TITLE
fix readable One-dimensional numpy.

### PR DESCRIPTION
**Pull request by toyama0919**
fix readable One-dimensional numpy.

example.

```py
import numpy
from imgcat import imgcat

path = 'evaluation/car1.jpg'
with open(path, 'rb') as f:
    data = numpy.frombuffer(f.read(), dtype="uint8")

print(data.shape) # => (37379,) one-dimensional ndarray
imgcat(data)
```

### CODE REVIEW

**Comment by wookayin** [comment]
Why do we need to support 1-dimensional ndarray? One can't tell the height/width of the image from the ndarray itself.

**Comment by toyama0919** [comment]
I think one-dimensional ndarray has reversibility, that image.

nd = numpy.frombuffer(f.read(), dtype="uint8")
nd.tostring() is image, nd.tostring() is bytes.

So I think readable imgcat.

**Comment by wookayin** [comment]
Well, I think in such cases users should explicitly use as `imgcat(arr.tostring())`.

**Comment by wookayin** [comment]
I am not going to have this merged. For byte-streams an explicit conversion from user side would be required.

**Comment by toyama0919** [comment]
understand.　Thank you!

**Pull request closed without merging**
